server:
  port: 8085

spring:
  application:
    name: hr

  mail:
    host: smtp.gmail.com
    port: 587
    username: mkinzy71@gmail.com
    password: diai gaml otre ripf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3307/internshipt_db
    username: kinzy
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


