server:
  port: 8081

spring:
  application:
    name: student
    main:
      allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3307/internshipt_db
    username: kinzy
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: student
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  httpclient:
    enabled: true

#logging:
#  file:
#    name: project-logs.log
#  level:
#    root: INFO
logging:
  level:
    com.netflix.discovery: ERROR
    com.netflix.discovery.shared.transport: ERROR
    com.fasterxml.jackson.databind: ERROR
    org.glassfish.jersey: ERROR

