server:
  port: 8082  # Unique port (different from student module)

spring:
  application:
    name:  INTERNSHIP # Clear service naming convention
    main:
      allow-bean-definition-overriding: true  # Prevents bean conflicts

  datasource:
    url: jdbc:mysql://localhost:3307/internshipt_db
    username: kinzy
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    # Force fresh registration
    should-enforce-registration-at-init: true
    should-unregister-on-shutdown: true

  instance:
    appname:  INTERNSHIP # Explicit Eureka service name
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  httpclient:
    enabled: true

# Optional: Add debug logging for Eureka
logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG